export const GETALL_TRAVELS_SUCCESS = "GETALL_TRAVELS_SUCCESS";
export const DELETE_TRAVELS_SUCCESS = "DELETE_TRAVELS_SUCCESS";
export const POST_TRAVELS_SUCCESS = "POST_TRAVELS_SUCCESS";
export const UPDATE_TRAVELS_SUCCESS = "UPDATE_TRAVELS_SUCCESS";

export const GETALL_USERS_SUCCESS = "GETALL_USERS_SUCCESS";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export const POST_USERS_SUCCESS = "POST_USERS_SUCCESS";
export const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS";

export const GETALL_RESERVATION_SUCCESS = "GETALL_RESERVATION_SUCCESS";
export const DELETE_RESERVATION_SUCCESS = "DELETE_RESERVATION_SUCCESS";
export const POST_RESERVATION_SUCCESS = "POST_RESERVATION_SUCCESS";
export const UPDATE_RESERVATION_SUCCESS = "UPDATE_RESERVATION_SUCCESS";
