export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const RESERVATION_SUCCESS = "RESERVATION_SUCCESS";
export const RESERVATION_FAILED = "RESERVATION_FAILED";

export const GETALL_TRAVELS = "GETALL_TRAVELS";
export const GETALL_TRAVELS_FAILED = "GETALL_TRAVELS_FAILED";

export const FORGOTPASSWORD_SUCCESS = "FORGOTPASSWORD_SUCCESS";
export const FORGOTPASSWORD_FAILED = "FORGOTPASSWORD_FAILED";

export const RESETPASSWORD_SUCCESS = "RESETPASSWORD_SUCCESS";
export const RESETPASSWORD_FAILED = "RESETPASSWORD_FAILED";

export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILED = "PAYMENT_FAILED";

export const POSTDISCOUNT_SUCCESS = "POSTDISCOUNT_SUCCESS";
export const POSTDISCOUNT_FAILED = "POSTDISCOUNT_FAILED";

export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
export const FACEBOOK_LOGIN_FAILED = "FACEBOOK_LOGIN_FAILED";

export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAILED = "GOOGLE_LOGIN_FAILED";
