export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const RESERVATION_SUCCESS = "RESERVATION_SUCCESS";
export const GETALL_TRAVELS = "GETALL_TRAVELS";
